name: CI/CD Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QUEMU
        uses: docker/setup-quemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: coders-school/desktop-business-app:latest
          # We could give some condition later to push the image to the registry
          push: false

      - name: Run Tests
        run: |
          docker run --rm coders-school/desktop-business-app:latest
